### ISSUE TITLE
Truncated RSS Feed

### ISSUE THREAD

**Issue by pstn** [NixOS/nixos-weekly#29]
I'd love to read the entire nixos weekly in my feed reader. Is there a reason why you don't allow that?
I know many commercial websites only use a truncated feed to force you to click on their site and watch the adds, but there is nothing here, so I don't see any harm in putting the whole article in the feed.

**Comment by garbas** [comment]
@pstn :+1: would you be able to provide a PR for this?

I hope this is as easy as finding the right setting for ``pelicanconf.py`` from http://docs.getpelican.com/en/stable/settings.html

**Comment by pstn** [comment]
It was.
https://github.com/NixOS/nixos-weekly/pull/30
