### ISSUE TITLE
This happened last week, but LLVM 4 is default stdenv for Darwin now

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixos-weekly#34]
Just another potential news item for next time 😄

It shouldn't have too many user-facing changes but a ton of behind-the-scenes work went into fixing the various packages that were incompatible with it to enable the upgrade.

**Comment by garbas** [comment]
Could you add a comment on #35 in a form of title & description

any link to potential PRs would be nice to have so that interested can look at changes
that way we can also give credits in public to people working on this
