### ISSUE TITLE
add editor's guide

### ISSUE THREAD

**Issue by badmutex** [NixOS/nixos-weekly#39]
I think it would be helpful to have an `EDITORS.rst` with general guidelines and some concrete examples of what to do as an editor. Hopefully this can make it easier for new editors.

# Proposed changes

- add `EDITORS.rst` to the top level
- link to `EDITORS.rst` from the README along with brief description

If there is agreement I can work on an initial outline and submit a PR.

**Comment by garbas** [comment]
Closing this since I just merged #45
