### ISSUE TITLE
Revive nixos-weekly

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixos-weekly#40]
It looks like this fizzled out. Any chance we can revive it? I would be willing to do one week.

Perhaps alternatively nixos-weekly is too often... Maybe monthly would be an easier target?

**Comment by AndersonTorres** [comment]
Once a month, maybe with arbitrary drops, like the "This Week in Rust"?

**Comment by garbas** [comment]
@matthewbauer @AndersonTorres ups sorry, I didn't see this issue sooner. I'm working on next (revived) edition of NixOS weekly (https://twitter.com/garbas/status/943953673096515584), it should be out

Would you like to contribute in the future? I would really appreciate any help, review, automation of stats, editing, coordinating ... I understand it is hard to commit for something like this, all I ask is that you give best you can and if you wont manage to do it that you ask for help, so other can step in. Would that work for you?

**Comment by AndersonTorres** [comment]
I would really like to help on it!

**Comment by olejorgenb** [comment]
The new bash completions for nix-* is a candidate to mention: https://github.com/hedning/nix-bash-completions

**Comment by zimbatm** [comment]
[nix-diff](http://www.haskellforall.com/2017/11/compare-nix-derivations-using-nix-diff.html) is super handy to find out why a derivation gets rebuilt.

[nix-deploy](https://github.com/awakesecurity/nix-deploy#readme)  has also been announced recently

**Comment by Profpatsch** [comment]
New PR is out, please move your entries here: https://github.com/NixOS/nixos-weekly/pull/41

**Comment by garbas** [comment]
@Profpatsch tnx. I was just about to close it and ping people there.
@zimbatm @olejorgenb don't worry i will include your comments in the newsletter, no need to duplicate the comments
@AndersonTorres awesome! would you like to do the next newsletter? And I will document the workflow as I'm explaining it to you, would that work for you?

**Comment by AndersonTorres** [comment]
Well, I have no special idea on how to help :) 
I consider myself in a beginner stage, I have almost nothing to contribute in terms of hints&tricks [F].
But if something else is needed, I can help.

The workflow: Yes, please explain.

F - On the other hand, I want to take that year to port Nix to FreeBSD.

**Comment by garbas** [comment]
@AndersonTorres What is mostly needed is that there is somebody that can be the person in charge to include the news in merge them, like i'm doing in https://github.com/NixOS/nixos-weekly/pull/41. And when the publishing day come that you announce the nixos weekly on all the channels.

I'm working on the docs right now and there should be something more for you to follow if you want to help with next newsletter.
