### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-weekly#42]
This ticket is meant as a place editors coordinate.

Currently the process how to publish a newsletter is not documented. This will (must) get done soon as part of #39, then collaboration can really start.

# Active editors

- @garbas
- @badi 

If you are interested in helping please drop a comment or add yourself directly to the list above.

**Comment by badmutex** [comment]
Hi. I can take issue 2018/02 and work on #39 concurrently. Better late than never I suppose :)

**Comment by matthewbauer** [comment]
I can do at least one week when needed.

**Comment by badmutex** [comment]
Thats great! Would you like to do the next issue? I'm happy to help as well.

**Comment by domenkozar** [comment]
As I've taken the weekly from @garbas, I'll try to do these each week and do a call for backup editor one day. More in https://github.com/NixOS/nixos-weekly/commit/4dd48dfec16e8812c3b6d2a1dee9224d63a37924
