### ISSUE TITLE
Are you interested in hearing about nixWRT?

### ISSUE THREAD

**Issue by telent** [NixOS/nixos-weekly#43]
It's a super-provisional project name because I haven't thought of a better one, but I recently posted to nix-devel about using Nix to build an image for embedded systems of the kind you'd typically run OpenWRT/DD-WRT etc on (consumer broadband routers etc)

Progress is slow but generally ongoing.

https://groups.google.com/forum/#!topic/nix-devel/zDQH7Ulotoc

I am blogging it in excruciating detail on my own site but if there's anything particular you want to know then reply to this issue and I'll write something especially for the Weekly

**Comment by garbas** [comment]
@telent 💯 will be included in next newsletter #46
