### ISSUE TITLE
Merge to production: new edition not added to gh-pages

### ISSUE THREAD

**Issue by badmutex** [NixOS/nixos-weekly#47]
I merged #46 and [travis build succeeded](https://travis-ci.org/NixOS/nixos-weekly/builds/335941882) but the new issue isn't reflected at at http://weekly.nixos.org

The log shows
```
==========================================================
No changes. Nothing to commit
==========================================================
```

**Comment by garbas** [comment]
looks like https://github.com/NixOS/nixos-weekly/commit/9259deb4d9b4ae5baec3c5039ce2e4bc9e29a6a7 fixed it. 2018/02 is live. i think i was missing one semicolon.
