### ISSUE TITLE
Collection of silly Nix references

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-weekly#53]
Just starting this collection for future posts. We already have the citation, we could also add some more visual things.

**Comment by zimbatm** [comment]
https://dawnofmidi.bandcamp.com/track/nix

**Comment by zimbatm** [comment]
![Hydra and Nix](http://en.es-static.us/upl/2015/07/nix-hydra-new-horizons-7-14-20151.jpg)
source: http://earthsky.org/space/pluto-moons-nix-and-hydra-revealed

**Comment by zimbatm** [comment]
![Nix lice treatment](https://i5.walmartimages.com/asr/91b1f1ed-aea6-4ce7-a252-40d7fcf2fb46_1.96cb013abe9c0eafcaddbd5306ad761d.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF)

**Comment by zimbatm** [comment]
![Nix and Kix](https://www.ocado.com/productImages/350/350489011_0_640x640.jpg?identifier=a6d7aa1718a081380d9c2332c687f442)
source: https://nixandkix.com/

**Comment by zimbatm** [comment]
![Nix ex machina](http://www.blackcomedy.co.uk/images/nix_ex_machina_cover_lrg.jpg)
source: http://www.blackcomedy.co.uk/nix_ex_machina_cover.html

**Comment by zimbatm** [comment]
A not very generous lender:
![Nix lending](https://www.nixlending.com/app/themes/salient-child/images/logo-en.png)
source: https://www.nixlending.com/

**Comment by zimbatm** [comment]
The nix sensor very accurate measures nothing all the time:
![Nix sensor](https://gadgetflowcdn.com/wp-content/uploads/2017/08/Nix-Mini-Color-Sensor-001.jpg)
source: https://thegadgetflow.com/portfolio/mini-color-sensor/

**Comment by uralbash** [comment]
![](http://toplogos.ru/images/logo-nix.gif)
https://nix.ru

**Comment by AndersonTorres** [comment]
https://en.wikipedia.org/wiki/Nix_v._Hedden

A SCOTUS case deciding if tomato is a vegetable or a fruit (for the effects of some tax laws)...

**Comment by zimbatm** [comment]
`John Nix` is an awesome name.

Now that we have Discourse I think those could be posted in the [links section](https://discourse.nixos.org/c/links). Another option is to pull some of these for each nixos weekly publication. /cc @domenkozar

**Comment by zimbatm** [comment]
![](https://pbs.twimg.com/media/Dlo31VaX4AAXEhX.jpg)

https://twitter.com/NIXplatform

**Comment by davidak** [comment]
I don't want to ruin the party, but using random images from the internet has copyright problems.
In most cases, you are not allowed to use them and still doing so can lead to legal difficulties.

**Comment by domenkozar** [comment]
I agree. I'm including quotes for each post and I'm not sure I want to add more things that aren't essential to the process.

**Comment by davidak** [comment]
@domenkozar you could have a funny picture instead of a quote, but it has to be under an open license.
