### ISSUE TITLE
Anduril Industries Job Posting

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixos-weekly#55]
Hi! I was wondering if you'd consider adding [Anduril Industries](https://www.anduril.com) to the Jobs section in the next issue? The job won't consist entirely of Nix work, but will also include work in other functional programming languages (we're using Haskell and Rust as well). We're using roughly this blurb:

> Anduril Industries (https://www.anduril.com) is hiring. TL;DR: Come write Haskell, Rust, and Nix (and some C++ when necessary) to make autonomous robots and drones go!
>
>We're a team of software and hardware engineers from various backgrounds (game development, computer graphics, financial technology, government intelligence, biotechnology) working to improve the state of defense technology. Our strategy involves focusing on product development instead of traditional governmental processes. By funding product development ourselves instead of relying on government funds, we're able to create more focused products faster and with significantly fewer resources. By leveraging hardware and techniques that have only recently become feasible to deploy at scale (e.g. GPGPU computing), we can significantly advance the state of the defense technology market.
>
>We're searching for generally competent, mathematically inclined software engineers, and we're especially interested in those with experience in computer vision (first principles techniques and machine learning), sensor fusion, detection and tracking, and statistical parameter estimation. Our team is increasingly applying functional programming and related technologies; we run Haskell and Rust code in production and use Nix to achieve reproducible build environments and keep deployment, CI, and cross-compilation sane.
>
>If you like FP, interfacing with hardware, and solving problems in detection, tracking, and autonomous vehicle control (land and air), drop me a line at travis-at-anduril-dot-com.

Thanks!

**Comment by domenkozar** [comment]
Hi @TravisWhitaker - I'm rebooting this project, is this job post still relevant? If so, I'd ask you to write 1-2 sentances and a link to the job post.

**Comment by domenkozar** [comment]
@TravisWhitaker if you'd like the job posting to go out next week, please do as I previously asked and post the content to https://github.com/NixOS/nixos-weekly/pull/59

Thank you!

**Comment by TravisWhitaker** [comment]
Apologies for the delay; I'll comment over there. Thanks!
