### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-weekly#58]
Hi,

Had an idea while reading this week's nixos-weekly. Tried it.

![nixos-weekly](https://user-images.githubusercontent.com/132835/43218785-6b74f0d8-9013-11e8-87a0-738407db0197.png)

It directly integrates the lambda from the lambdaflake in the middle. Integrating something else than a plain bar to the left was clumsy. To the right, it looked possible to integrate a lambda, but it makes the logo seem messier than simply continuing the line already present.

If anyone wants to play around, there are plenty of guides (the lines in inkscape).

 * https://github.com/samueldr/nixos-artwork/blob/weekly/weekly/nixos-weekly.svg

* * *

Oh, *after* doing this, I thought about searching "haskell weekly", to see if they did something similar.

 * https://haskellweekly.news/

They did. There are no original ideas in life!

**Comment by domenkozar** [comment]
Nice! :) I like it, let's wait for some more feedback, otherwise, I'll just add it.

**Comment by domenkozar** [comment]
Thanks, it already can be seen on http://weekly.nixos.org/preview/2018/
