### ISSUE TITLE
a script to create stats for issues/PRs

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-weekly#6]
we need a script that you would execute as:

```
% ./result/bin/github-stats NixOS/nixpkgs 2016-08-01
```

first argument would accept a short handle for github repository (that way we can run this against multiple nix related projects).

second argument is a date from which we want result to be summed together. we would run this script on the day of a blog release and we would provide a date with last blog release. 

above script would output json to stdout in following format

```
{
  new_issues: 13,
  closed_issued: 10,
  new_pr: 4,
  closed_pr: 20
}
```

i think above is not the final version of this script, but MVP which should be easy to get done in few hours.

**Comment by grahamc** [comment]
I would be happy to do this. I think the best way to do this is with something more structured than bash / curl / jq, and if you're okay with that I'll make it happen.

**Comment by garbas** [comment]
@grahamc that would be fantastic. i'll update the ticket description to be more detailed

**Comment by garbas** [comment]
description updated ... let me know if this makes sense.

**Comment by grahamc** [comment]
Yep. On it. Thanks!
