### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixos-weekly#70]
Accessing http://weekly.nixos.org should redirect to https://weekly.nixos.org.

The certificate is already there, only the redirect is missing :)

**Comment by asymmetric** [comment]
Actually even better than a server-side redirect would be [HSTS](https://infosec.mozilla.org/guidelines/web_security#http-strict-transport-security).

**Comment by zimbatm** [comment]
it's also really simple to do: https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site

/cc @domenkozar

**Comment by domenkozar** [comment]
Done :)
