### ISSUE TITLE
Use netlify

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-weekly#80]
It's 2019, let's use a proper CD and deprecate preview hack.

**Comment by AndersonTorres** [comment]
What is it?

**Comment by domenkozar** [comment]
https://netlify.com

**Comment by domenkozar** [comment]
Last bits missing:

- [x] remove all CI complexity
- [x] CNAME https://nixos-weekly.netlify.com/

**Comment by domenkozar** [comment]
All done
