### ISSUE TITLE
Arcesium LLC is hiring for Infrastructure Engineer

### ISSUE THREAD

**Issue by ShrutiG94** [NixOS/nixos-weekly#97]
Join the infrastructure team of a fintech company using AWS, Kubernetes, Python, Haskell, and Nix to build a declarative infrastructure. We're looking for someone experienced in design, development, and systems engineering. Compensation is competitive.

To know more about the job and us, please visit https://arcesium.com/careers.html

**Comment by domenkozar** [comment]
@ShrutiG94 I don't see Nix mentioned in the job description, can you make sure that's the case?
